name: Tests
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - id: go-version
      run: echo "::set-output name=version::$(cat ./.go-version)"
    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ${{ steps.go-version.outputs.version }}
      id: go

    - name: Go fmt
      run: |
        make fmt

    - name: Go vet
      run: |
        make vet

    - name: Build
      run: |
        go build -v .


# run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '0.12.*'
          - '0.13.*'
          - '0.14.*'
          - '0.15.*'
          - '1.0.*'
          - '1.1.*'
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - id: go-version
      run: echo "::set-output name=version::$(cat ./.go-version)"
    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ${{ steps.go-version.outputs.version }}
      id: go
    - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    # See also: https://github.com/hashicorp/setup-terraform/issues/143
    - run: terraform version
    - run: go mod download
    - name: TF acceptance tests
      timeout-minutes: 10
      env:
        TF_ACC: "1"
      run: go test -v -cover ./internal/provider/
